       
void Pink(void **o, long a) __attribute__((section(".text." "Pink"))) __attribute__((noinline)); void Pink(void **o, long a) { asm("nop" : : "a"(o + a)); }
void Olive(void **o, long a) __attribute__((section(".text." "Olive"))) __attribute__((noinline)); void Olive(void **o, long a) { asm("nop" : : "a"(o + a)); } void Maroon(void **o, long a) __attribute__((section(".text." "Maroon"))) __attribute__((noinline)); void Maroon(void **o, long a) { asm("nop" : : "a"(o + a)); } void Lime(void **o, long a) __attribute__((section(".text." "Lime"))) __attribute__((noinline)); void Lime(void **o, long a) { asm("nop" : : "a"(o + a)); } void Aqua(void **o, long a) __attribute__((section(".text." "Aqua"))) __attribute__((noinline)); void Aqua(void **o, long a) { asm("nop" : : "a"(o + a)); } void Blue(void **o, long a) __attribute__((section(".text." "Blue"))) __attribute__((noinline)); void Blue(void **o, long a) { asm("nop" : : "a"(o + a)); } void Green(void **o, long a) __attribute__((section(".text." "Green"))) __attribute__((noinline)); void Green(void **o, long a) { asm("nop" : : "a"(o + a)); } void Red(void **o, long a) __attribute__((section(".text." "Red"))) __attribute__((noinline)); void Red(void **o, long a) { asm("nop" : : "a"(o + a)); } void Yellow(void **o, long a) __attribute__((section(".text." "Yellow"))) __attribute__((noinline)); void Yellow(void **o, long a) { asm("nop" : : "a"(o + a)); } void Purple(void **o, long a) __attribute__((section(".text." "Purple"))) __attribute__((noinline)); void Purple(void **o, long a) { asm("nop" : : "a"(o + a)); }
void (*print)(char *, ...);
void Blue___ray(void **o, long a) __attribute__((noinline)); void Blue___(void **o, long a) __attribute__((section(".text." "Blue___"))); void Blue___(void **o, long a) { Blue___ray(o, a); } void Blue___ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Blue(o, a); }
void Green__ray(void **o, long a) __attribute__((noinline)); void Green__(void **o, long a) __attribute__((section(".text." "Green__"))); void Green__(void **o, long a) { Green__ray(o, a); } void Green__ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Green(o, a); }
void Red____ray(void **o, long a) __attribute__((noinline)); void Red____(void **o, long a) __attribute__((section(".text." "Red____"))); void Red____(void **o, long a) { Red____ray(o, a); } void Red____ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Red(o, a); }
void Yellow_ray(void **o, long a) __attribute__((noinline)); void Yellow_(void **o, long a) __attribute__((section(".text." "Yellow_"))); void Yellow_(void **o, long a) { Yellow_ray(o, a); } void Yellow_ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Yellow(o, a); }
void Purple_ray(void **o, long a) __attribute__((noinline)); void Purple_(void **o, long a) __attribute__((section(".text." "Purple_"))); void Purple_(void **o, long a) { Purple_ray(o, a); } void Purple_ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Purple(o, a); }
void Pink___ray(void **o, long a) __attribute__((noinline)); void Pink___(void **o, long a) __attribute__((section(".text." "Pink___"))); void Pink___(void **o, long a) { Pink___ray(o, a); } void Pink___ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Pink(o, a); }
void Olive__ray(void **o, long a) __attribute__((noinline)); void Olive__(void **o, long a) __attribute__((section(".text." "Olive__"))); void Olive__(void **o, long a) { Olive__ray(o, a); } void Olive__ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Olive(o, a); }
void Maroon_ray(void **o, long a) __attribute__((noinline)); void Maroon_(void **o, long a) __attribute__((section(".text." "Maroon_"))); void Maroon_(void **o, long a) { Maroon_ray(o, a); } void Maroon_ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Maroon(o, a); }
void Lime___ray(void **o, long a) __attribute__((noinline)); void Lime___(void **o, long a) __attribute__((section(".text." "Lime___"))); void Lime___(void **o, long a) { Lime___ray(o, a); } void Lime___ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Lime(o, a); }
void Aqua___ray(void **o, long a) __attribute__((noinline)); void Aqua___(void **o, long a) __attribute__((section(".text." "Aqua___"))); void Aqua___(void **o, long a) { Aqua___ray(o, a); } void Aqua___ray(void **o, long a) { print = o[0], print("%s:%s\n", aword, m.c),((void (**)(long))o)[1](200000), Aqua(o, a); }
